# Generated by Django 3.2.18 on 2023-04-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.TextField()),
                ('u_mail', models.TextField()),
                ('u_job', models.TextField()),
                ('u_msg', models.TextField()),
            ],
        ),
    ]
